---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: paperless-server
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: server

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/component: server

  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: server

    spec:
      enableServiceLinks: false

      containers:
        - name: server
          image: paperless-server
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: paperless-server
            - secretRef:
                name: paperless-server

          ports:
            - name: http
              containerPort: 8000

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 50
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 50
            periodSeconds: 10

...
