---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: paperless-server
    options:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: server
    literals: []

secretGenerator:
  - name: paperless-server
    options:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: server
    literals: []

images:
  - name: paperless-server
    newName: ghcr.io/paperless-ngx/paperless-ngx
    newTag: "2.8.0"

...
