---
apiVersion: v1
kind: Service

metadata:
  name: paperless-server
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 8000

...
