---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: paperless-tika
  labels:
    app.kubernetes.io/name: paperless
    app.kubernetes.io/component: tika

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/component: tika

  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: tika

    spec:
      enableServiceLinks: false

      containers:
        - name: server
          image: paperless-tika
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: paperless-tika
            - secretRef:
                name: paperless-tika

          ports:
            - name: http
              containerPort: 9998

          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 50
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 50
            periodSeconds: 10

...
