---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: paperless-tika
    options:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: tika
    literals: []

secretGenerator:
  - name: paperless-tika
    options:
      labels:
        app.kubernetes.io/name: paperless
        app.kubernetes.io/component: tika
    literals: []

images:
  - name: paperless-tika
    newName: ghcr.io/paperless-ngx/tika
    newTag: "2.9.1-minimal"

...
